### ISSUE TITLE
Copy command failing via odyssey

### ISSUE THREAD

**Issue by evkuzin** [yandex/odyssey#554]
Hi guys. Odyssey doesn't seem to support copy command. Is it known? Are there any plans? Is it a bug? 

against postgres directly:

```
$ for i in {1..1000}; do echo "run_id_${i},task_id_${i},Some random ${i}th text"; done | psql postgresql://earth_adm@shapgearthpipelinea03:5433/earth -c "COPY testing FROM STDIN (FORMAT csv);";
COPY 1000
```

Via odysssey
```
$ for i in {1..1000}; do echo "run_id_${i},task_id_${i},Some random ${i}th text"; done | psql postgresql://earth_adm@shapgearthpipelinea03:5432/earth -c "COPY testing FROM STDIN (FORMAT csv);";
ERROR:  unexpected message type 0x00 during COPY from stdin
CONTEXT:  COPY testing, line 167
ERROR:  unexpected message type 0x00 during COPY from stdin
CONTEXT:  COPY testing, line 167
FATAL:  terminating connection because protocol synchronization was lost
```

**Comment by x4m** [comment]
AFAIK this was fixed in https://github.com/yandex/odyssey/commit/6ea14ee8bfb02941ca2a1dbefa7b8fa00c00ec71

**Comment by evkuzin** [comment]
Would have been nice, but I'm using binary build with [this](https://github.com/yandex/odyssey/pull/547/commits/f9e6176c21ce807ee5be7ecf0ba84fec38e458cb) and it is much older. Error is still there 🤷

**Comment by evkuzin** [comment]
@reshke seems like your fix wasn't enough to fix COPY :(

**Comment by evkuzin** [comment]
🤦 Yup, I meant newer 🤣

**Comment by evkuzin** [comment]
Update. 
The issue is with 
```
pool_reserve_prepared_statement yes
```
in the config
Without it, everything works like a charm.
